<div class="cleared reset-box"></div>
	<div class="header">
		<div class="header-position">
			<div class="header-wrapper">
			<div class="cleared reset-box"></div>
				<div class="header-inner">
					<div class="logo">
					<h1 class="logo-name"><a href="/openhouse/">Astronomy Observatory</a></h1>
					<h2 class="logo-text">Department of Astronomy, University of Maryland
					<br>College Park, MD</h2>
					</div>
				</div>
			</div>
		</div>
	</div>
<div class="cleared reset-box"></div>