<div class="bar nav">
<div class="nav-outer">
<div class="nav-wrapper">
<div class="nav-inner">
<div class="nav-center">
<ul class="hmenu">
	<li><a href="/openhouse/">Home</a></li>
	<li><a href="/openhouse/1visiting/visiting.html">Visiting</a>
		<ul>
		<li><a href="/openhouse/1visiting/logistics.html">Visiting Logistics</a></li>
		<li><a href="/openhouse/1visiting/directions.html">Directions/Maps</a></li>
		<li><a href="/openhouse/1visiting/reservations.html">Reservations</a></li>
		<li><a href="/openhouse/1visiting/groups.html">Groups</a></li>
		<li><a href="/openhouse/1visiting/students.html">Individual Students</a></li>
		<li><a href="/openhouse/1visiting/special-needs.html">Special Needs</a></li>
		<li><a href="/openhouse/1visiting/media.html">Media Requests</a></li>
		</ul></li>
	<li><a href="/openhouse/2programs/programs.html">Programs</a>
		<ul>
		<li><a href="/openhouse/2programs/open-house.html">Open House</a></li>
		<li><a href="/openhouse/2programs/new-telescope-owners-nights.html">New Telescope Owners Nights</a></li>
		<li><a href="/openhouse/2programs/learn-the-sky-nights.html">Learn the Sky Nights</a></li>
		<li><a href="/openhouse/2programs/special-events.html">Special Events</a></li>
		<li><a href="/openhouse/2programs/impromptu.html">Impromptu</a></li>
		<li><a href="/openhouse/2programs/wow.html">Working Obs. Wednesdays</a></li>
		</ul></li>
	<li><a href="/openhouse/3about-the-obs/about-the-obs.html" class="active">About the Obs.</a>
		<ul>
		<li><a href="/openhouse/3about-the-obs/about-the-obs.html#history">History</a></li>
		<li><a href="/openhouse/3about-the-obs/about-the-obs.html#facility">Facility</a></li>
		<li><a href="/openhouse/3about-the-obs/telescopes.html">Telescopes</a></li>
		<li><a href="/openhouse/3about-the-obs/friends.html">Friends</a></li>
		<li><a href="/openhouse/3about-the-obs/in-the-news.html">In the News...</a></li>
		<li><a href="/openhouse/3about-the-obs/newsletter.html" class="active">Newsletter</a></li>
		</ul></li>
	<li><a href="/openhouse/4observing-resources/observing-resources.html">Observing Resources</a>
		<ul>
		<li><a href="/openhouse/4observing-resources/telescope-advice.html">Telescope Advice</a></li>
		<li><a href="/openhouse/4observing-resources/aurora.html">Aurora</a></li>
		<li><a href="/openhouse/4observing-resources/satellites.html">Satellites</a></li>
		<li><a href="/openhouse/4observing-resources/weather.html">Weather</a></li>
		</ul></li>
	<li><a href="/openhouse/5gallery/gallery.html">Gallery</a>
		<ul>
		<li><a href="/openhouse/5gallery/sky.html">Sky</a></li>
		<li><a href="/openhouse/5gallery/gallery.html#events">Events</a></li>
		<li><a href="/openhouse/5gallery/EarthDial.html">EarthDial</a></li>
		<li><a href="/openhouse/5gallery/visitors.html">Visitors</a></li>
		</ul></li>
	<li><a href="/openhouse/6telescope-ops/telescope-ops.html">Telescope Ops.</a>
		<ul>
		<li></li>
		</ul></li>
	<li><a href="/openhouse/7research/research-summary.html">Research</a>
		<ul>
		<li></li>
		</ul></li>
</ul>
</div>
</div>
</div>
</div>
</div>
<div class="cleared reset-box"></div>