<div class="cleared"></div>
<div class="footer">
<div class="footer-body">
	<div class="footer-text">
	<p><a href="/openhouse/contact.html">Contact</a> | <a href="/openhouse/sitemap.html">Sitemap</a> | <a href="/openhouse/search.html">Search</a>
	<br><a href="/">Astronomy Dept</a> | <a href="http://www.cmns.umd.edu/">CMNS</a> | <a href="http://www.umd.edu/">UMD</a>
	<br><em><strong><a href="https://umd.edu/web-accessibility" target="_blank">Web Accessibility</a></strong></em></p>
	<p>Copyright &copy; 2024. All Rights Reserved.</p>
	</div>
<div class="cleared"></div>
</div>
</div>