<div class="box block">
<div class="box-body block-body">

	<div class="bar blockheader">
	<h3 class="t">Local Astronomy</h3>
	</div>

	<div class="box blockcontent">
	<div class="box-body blockcontent-body">
	<div>
	<ul>
	<li><a href="https://terplink.umd.edu/organization/astroterps">AstroTerps</a></li>
	<li><a href="https://www.astro.umd.edu/">UMD Dept of Astronomy</a><br><br></li>
	
	<li><a href="http://astronomyindc.org/">Astronomy in DC</a><br>(for a fuller list of clubs, observatories, planetariums in the region)<br><br></li>
	<li><a href="http://capitalastronomers.org/">National Capital Astronomers</a></li>
	<li><a href="http://www.greenbeltastro.org/">Astronomical Society of Greenbelt</a></li>
	<li><a href="http://www.howardastro.org/">Howard Astronomical League</a></li>
	<li><a href="https://www.novac.com/wp//">Northern VA Astronomy Club</a></li>
	</ul>
	</div>
	<div class="cleared"></div>
	</div>
	</div>

<div class="cleared"></div>
</div>
</div>