<div class="box block">
<div class="box-body block-body">

	<div class="bar blockheader">
	<h3 class="t">Next Open House</h3>
	</div>

	<div class="box blockcontent">
	<div class="box-body blockcontent-body">
	
	
	<p>
	<!-- 12/20&nbsp;&nbsp;8pm<br><a href="/openhouse/2programs/oh/oh_19C.html#"><strong>Dr. Erez Michaely</strong></a><br>&quot;Gravitational Dynamics: From Apples to Black-holes&quot; --><!-- 2020 -->
	<!-- 1/05&nbsp;&nbsp;8pm<br><a href="/openhouse/2programs/oh/oh_20A.html#warner"><strong>Elizabeth Warner</strong></a><br>&quot;2020 Observing Highlights&quot; -->
	<!-- 1/20&nbsp;&nbsp;8pm<br><a href="/openhouse/2programs/oh/oh_20A.html#warner2"><strong>Elizabeth Warner</strong></a><br>&quot;Sky Tour&quot; -->
	<!-- 2/05&nbsp;&nbsp;8pm<br><a href="/openhouse/2programs/oh/oh_20A.html#troja"><strong>Dr. Eleonora Troja</strong></a><br>&quot;Gravitational Waves, Light, and the Origin of Gold&quot; -->
	<!-- 2/20&nbsp;&nbsp;8pm<br><a href="/openhouse/2programs/oh/oh_20A.html#bolatto"><strong>Dr. Alberto Bolatto</strong></a><br>&quot;The Evolution of Galaxies through Cosmic Time&quot; -->
	<!-- 3/05&nbsp;&nbsp;8pm<br><a href="/openhouse/2programs/oh/oh_20A.html#deming"><strong>Dr. Drake Deming</strong></a><br>&quot;New Exoplanets from the TESS Mission&quot; -->
	<!-- <em>In order to meet necessary precautions, the Observatory is canceling its Open Houses through May.</em> -->
	<!-- <span class="red">CANCELED</span> - 3/20&nbsp;8pm<br><a href="/openhouse/2programs/oh/oh_20A.html#knight"><strong>Dr. Matthew Knight</strong></a><br>&quot;The Galaxy Strikes Back: What have we learned after visits by two interstellar objects?&quot -->
	<!-- <span class="red">CANCELED</span> - 4/05&nbsp;8pm<br><a href="/openhouse/2programs/oh/oh_20A.html#cosentino"><strong>Dr. Richard Cosentino</strong></a><br>&quot;Storms and Climate of Jupiter and Saturn&quot; -->
	<!-- <span class="red">CANCELED</span> - 4/20&nbsp;8pm<br><a href="/openhouse/2programs/oh/oh_20A.html#agrusa"><strong>Harrison Agrusa</strong></a><br>&quot;DART: NASA's First Mission to Deflect an Asteroid&quot; -->
	<!-- <span class="red">CANCELED</span> - 5/05&nbsp;&nbsp;9pm<br><a href="/openhouse/2programs/oh/oh_20B.html#sugimura"><strong>Dr. Kazuyuki Sugimura</strong></a><br>&quot;The Birth of the First Stars in the Universe&quot; -->
	<!-- <span class="red">CANCELED</span> - 5/20&nbsp;&nbsp;9pm<br><a href="/openhouse/2programs/oh/oh_20B.html#crossley"><strong>Sam Crossley</strong></a><br>&quot;Understanding Asteroids through Meteorite Analogues&quot; -->
	<!-- <span class="red">CANCELED</span> - 6/05&nbsp;&nbsp;9pm<br><a href="/openhouse/2programs/oh/oh_20B.html#frederick"><strong>Sara Frederick</strong></a><br>&quot;From Tantrums to Transformations: The Lives of Active Supermassive Black Holes&quot;
	<span class="red">CANCELED</span> - 6/20&nbsp;&nbsp;9pm<br><a href="/openhouse/2programs/oh/oh_20B.html#shuster"><strong>Dr. Jason Shuster</strong></a><br>&quot;Magnetic Reconnection: The Universe's Favorite Way to Make Things Explode!&quot; -->
	<em>Due to budget cuts, the Observatory remains closed to public outreach activities.</em>
</p>
<hr />
<ul><!-- <li><a href="/openhouse/2programs/oh/oh_24C.html">Full Schedule</a></li> -->
<li><a href="/openhouse/2programs/open-house.html">About Open House</a></li>
</ul>
	
	
	
	<div class="cleared"></div>
	</div>
	</div>

<div class="cleared"></div>
</div>
</div>