<div class="box block">
<div class="box-body block-body">

	<div class="bar blockheader">
	<h3 class="t">Newsletter</h3>
	</div>

	<div class="box blockcontent">
	<div class="box-body blockcontent-body">
	<div>

<p>You can now <a href="/openhouse/3about-the-obs/newsletter.html">subscribe to get occasional emails</a> (~1/month) about UMD Observatory programs, local astro events, and interesting observing opportunities. The email is text-based... just a very informal newsletter that we will send out when we have several items of interest.</p>
<ul>
<li><a href="/openhouse/3about-the-obs/newsletter.html">Subscription details</a></li>
<li><a href="https://listserv.umd.edu/archives/observatory.html">Message Archive</a></li>
</ul>

	</div>
	<div class="cleared"></div>
	</div>
	</div>

<div class="cleared"></div>
</div>
</div>