<div class="box block">
<div class="box-body block-body">

	<div class="bar blockheader">
	<h3 class="t">Virtual Programs</h3>
	</div>

	<div class="box blockcontent">
	<div class="box-body blockcontent-body">
	<p>As we cruise around Facebook, we come across many virtual events taking place locally, nationally, and even internationally. We share those notifications on our FB page. You do not need to be on FB! Just check out the <strong>Social Networks</strong> box --&gt;<br> and you can scroll through the postings there.</p>
	
	
	<div class="cleared"></div>
	</div>
	</div>

<div class="cleared"></div>
</div>
</div>