<div class="box block">
<div class="box-body block-body">

	<div class="bar blockheader">
	<h3 class="t">Current Auroral Oval</h3>
	</div>

	<div class="box blockcontent">
	<div class="box-body blockcontent-body">
	<div class="aurora">

<a href="https://www.swpc.noaa.gov/products/aurora-30-minute-forecast"><img src="https://services.swpc.noaa.gov/images/aurora-forecast-northern-hemisphere.jpg" width="260" alt="northern auroral oval graphic" /></a>

<br><a href="/openhouse/4observing-resources/aurora.html">Read More...</a>
	</div>
	<div class="cleared"></div>
	</div>
	</div>

<div class="cleared"></div>
</div>
</div>