<div class="box block">
<div class="box-body block-body">

	<div class="bar blockheader">
	<h3 class="t">Comet PanSTARRS</h3>
	</div>

	<div class="box blockcontent">
	<div class="box-body blockcontent-body">
	
	
	<h6>Date:&nbsp;Decision</h6>
	<ul>
	<li>Fri 15 Mar: NO GO!</li>
	<li>Thu 14 Mar: GO!</li>
	<li>Wed 13 Mar: GO!</li>
	<li>Tue 12 Mar: GO!</li>
	<li>Mon 11 Mar: NO GO!</li>
	</ul>
	
	<div class="cleared"></div>
	</div>
	</div>

<div class="cleared"></div>
</div>
</div>