<div class="box block">
<div class="box-body block-body">

	<div class="bar blockheader">
	<h3 class="t">Open House Schedules</h3>
	</div>

	<div class="box blockcontent">
	<div class="box-body blockcontent-body">
	<div>
	
<h6>Current</h6>
<ul>
<li>Still Closed</li>
</ul>

<h6>Past</h6>
<ul>

<li>Spring 24, Summer 24, Fall 24</li>
<li>Spring 23, Summer 23, Fall 23</li>
<li>Spring 22, Summer 22, Fall 22</li>
<li>Spring 21, Summer 21, Fall 21</li>
<li><a href="/openhouse/2programs/oh/oh_20A.html">Spring 20</a>, <a href="/openhouse/2programs/oh/oh_20B.html">Summer 20</a>, <a href="/openhouse/2programs/oh/oh_20C.html">Fall 20</a></li>
<li><a href="/openhouse/2programs/oh/oh_19A.html">Spring 19</a>, <a href="/openhouse/2programs/oh/oh_19B.html">Summer 19</a>, <a href="/openhouse/2programs/oh/oh_19C.html">Fall 19</a></li>
<li><a href="/openhouse/2programs/oh/oh_18A.html">Spring 18</a>, <a href="/openhouse/2programs/oh/oh_18B.html">Summer 18</a>, <a href="/openhouse/2programs/oh/oh_18C.html">Fall 18</a></li>
<li><a href="/openhouse/2programs/oh/oh_17A.html">Spring 17</a>, <a href="/openhouse/2programs/oh/oh_17B.html">Summer 17</a>, <a href="/openhouse/2programs/oh/oh_17C.html">Fall 17</a></li>
<li><a href="/openhouse/2programs/oh/oh_16A.html">Spring 16</a>, <a href="/openhouse/2programs/oh/oh_16B.html">Summer 16</a>, <a href="/openhouse/2programs/oh/oh_16C.html">Fall 16</a></li>
<li><a href="/openhouse/2programs/oh/oh_15A.html">Spring 15</a>, <a href="/openhouse/2programs/oh/oh_15B.html">Summer 15</a>, <a href="/openhouse/2programs/oh/oh_15C.html">Fall 15</a></li>
<li><a href="/openhouse/2programs/oh/oh_14A.html">Spring 14</a>, <a href="/openhouse/2programs/oh/oh_14B.html">Summer 14</a>, <a href="/openhouse/2programs/oh/oh_14C.html">Fall 14</a></li>
<li><a href="/openhouse/2programs/oh/oh_13A.html">Spring 13</a>, <a href="/openhouse/2programs/oh/oh_13B.html">Summer 13</a>, <a href="/openhouse/2programs/oh/oh_13C.html">Fall 13</a></li>
<li><a href="/openhouse/2programs/oh/oh_12A.html">Spring 12</a>, <a href="/openhouse/2programs/oh/oh_12B.html">Summer 12</a>, <a href="/openhouse/2programs/oh/oh_12C.html">Fall 12</a></li>
<li><a href="/openhouse/2programs/oh/oh_11A.html">Spring 11</a>, <a href="/openhouse/2programs/oh/oh_11B.html">Summer 11</a>, <a href="/openhouse/2programs/oh/oh_11C.html">Fall 11</a></li>
<li><a href="/openhouse/2programs/oh/oh_10A.html">Spring 10</a>, <a href="/openhouse/2programs/oh/oh_10B.html">Summer 10</a>, <a href="/openhouse/2programs/oh/oh_10C.html">Fall 10</a></li>
<li><a href="/openhouse/2programs/oh/oh_09A.html">Spring 09</a>, <a href="/openhouse/2programs/oh/oh_09B.html">Summer 09</a>, <a href="/openhouse/2programs/oh/oh_09C.html">Fall 09</a></li>
<li><a href="/openhouse/2programs/oh/oh_08A.html">Spring 08</a>, <a href="/openhouse/2programs/oh/oh_08B.html">Summer 08</a>, <a href="/openhouse/2programs/oh/oh_08C.html">Fall 08</a></li>
<li><a href="/openhouse/2programs/oh/oh_07A.html">Spring 07</a>, <a href="/openhouse/2programs/oh/oh_07B.html">Summer 07</a>, <a href="/openhouse/2programs/oh/oh_07C.html">Fall 07</a></li>
<li><a href="/openhouse/2programs/oh/oh_06A.html">Spring 06</a>, <a href="/openhouse/2programs/oh/oh_06B.html">Summer 06</a>, <a href="/openhouse/2programs/oh/oh_06C.html">Fall 06</a></li>
<li><a href="/openhouse/2programs/oh/oh_05A.html">Spring 05</a>, <a href="/openhouse/2programs/oh/oh_05B.html">Summer 05</a>, <a href="/openhouse/2programs/oh/oh_05C.html">Fall 05</a></li>
<li><a href="/openhouse/2programs/oh/oh_04A.html">Spring 04</a>, <a href="/openhouse/2programs/oh/oh_04B.html">Summer 04</a>, <a href="/openhouse/2programs/oh/oh_04C.html">Fall 04</a></li>
<li><a href="/openhouse/2programs/oh/oh_03A.html">Spring 03</a>, <a href="/openhouse/2programs/oh/oh_03B.html">Summer 03</a>, <a href="/openhouse/2programs/oh/oh_03C.html">Fall 03</a></li>
<li><a href="/openhouse/2programs/oh/oh_02B.html">Summer 02</a>, <a href="/openhouse/2programs/oh/oh_02C.html">Fall 02</a></li>
</ul>

<h6>Archive</h6>
<ul>
<li><a href="/openhouse/2programs/oh/speakers_list_archive.doc">List of past speakers (doc)</a></li>
<li><a href="/openhouse/2programs/oh/speakers_list_archive.xls">List of past speakers (xls)</a></li>
</ul>
	
	</div>
	<div class="cleared"></div>
	</div>
	</div>

<div class="cleared"></div>
</div>
</div>