<div class="box block">
<div class="box-body block-body">

	<div class="bar blockheader">
	<h3 class="t">Search</h3>
	</div>

	<div class="box blockcontent">
	<div class="box-body blockcontent-body">
	<div>
	<form method="get" name="searchform" action="#">
	<input type="text" value="" name="s" style="width: 95%;" />
	 <span class="button-wrapper">
	<span class="button-l"> </span>
	<span class="button-r"> </span>
	<a class="button" href="javascript:void(0)">Search</a>
	</span> 
	
	</form>
	</div>
	<div class="cleared"></div>
	</div>
	</div>

<div class="cleared"></div>
</div>
</div>