<div class="box block">
<div class="box-body block-body">

	<div class="bar blockheader">
	<h3 class="t">Other Programs</h3>
	</div>

	<div class="box blockcontent">
	<div class="box-body blockcontent-body">
	<p>Coming up:</p>
	<ul>
	<!-- <li>Garage Sale!
	<br>+ Sat 27 July 4-8pm
	<br>+ Sun 28 July 12-8pm</li> -->
	
	<!-- <li><span class="red">CANCELED</span> through May<br><a href="/openhouse/2programs/wow.html">WOW!</a> 4-6pm<br><br></li> -->
	<li>VIRTUAL :: 12 Oct<br><a href="http://capitalastronomers.org/">NCA meeting</a>, 7:30pm<br><br></li>
	<li>This you can do on your own!!<br><a href="https://www.globeatnight.org/">Globe at Night</a>!</li>
	
	<!-- <li><a href="/openhouse/2programs/ltsn/Learn_the_sky18.html">Learn the Sky Nights 2018</a>
	<br>Classes start 10 Jul. Registration closes 9 July!</li> -->
	
	<!-- <li>20 Jan: Lunar Eclipse! (Stay tuned!)</li> -->

	<!-- <li>15 &amp; 18 Jan: <a href="/openhouse/2programs/new-telescope-owners-nights.html">New Telescope Owner Nights 2020</a>, registration now open!</li> -->
	</ul>

	<p>&nbsp;</p>
	<p>Mark your calendar!</p>
	
	<ul>
	
	<!-- <li>10 Nov: <a href="/openhouse/2programs/gear_swap.html">Astro Gear Swap</a></li> -->
	
	<li>26 April 2025: info about <a href="/openhouse/5gallery/events/MD_Day/MD_Day24.html">Maryland Day 2024!</a><br></li>

	<!-- <li>19 Sep 2015: <a href="https://moon.nasa.gov/observe-the-moon-night/">International Observe the Moon Night</a><br></li> -->
	
	</ul>
	
	<div class="cleared"></div>
	</div>
	</div>

<div class="cleared"></div>
</div>
</div>