<div class="box block">
<div class="box-body block-body">

	<div class="bar blockheader">
	<h3 class="t">Gallery quicklinks</h3>
	</div>

	<div class="box blockcontent">
	<div class="box-body blockcontent-body">
	<div>
	<ul>
	<li><a href="/openhouse/5gallery/sky.html">Sky</a></li>
	<li><a href="/openhouse/5gallery/gallery.html#events">Events</a></li>
	<li><a href="/openhouse/5gallery/EarthDial.html">EarthDial</a></li>
	<li><a href="/openhouse/5gallery/visitors.html">Visitors</a></li>
	</ul>
	</div>
	<div class="cleared"></div>
	</div>
	</div>

<div class="cleared"></div>
</div>
</div>