<div class="box block">
<div class="box-body block-body">

	<div class="bar blockheader">
	<h3 class="t">Weather at the Observatory</h3>
	</div>

	<div class="box blockcontent">
	<div class="box-body blockcontent-body">
	<div>

<ul>
<li><a href="/openhouse/4observing-resources/weather.html">satellite pics of region</a></li>
<li><a href="https://www.cleardarksky.com/c/UoMrylndOBMDkey.html" target="_blank">UMD Obs. Clear Sky Chart</a></li>
</ul>

<a href="https://www.cleardarksky.com/c/UoMrylndOBMDkey.html" target="_blank"><img src="https://www.cleardarksky.com/c/UoMrylndOBMDcs0.gif?1" alt="Click for UMD Obs Clear Sky Chart" width="250" onclick="this.target='_blank'" /></a>
<br><br><!-- 2020-12-12: new weather widget -->
<a class="weatherwidget-io" href="https://forecast7.com/en/38d99n76d94/college-park/?unit=us" data-label_1="COLLEGE PARK" data-label_2="WEATHER" data-font="Play" data-days="3" data-theme="original" >COLLEGE PARK WEATHER</a>
<script>
!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src='https://weatherwidget.io/js/widget.min.js';fjs.parentNode.insertBefore(js,fjs);}}(document,'script','weatherwidget-io-js');
</script><!-- old weather code; commented out 2020-12-12 --><!-- <a href="http://www.wunderground.com/US/MD/College_Park.html?bannertypeclick=sunandmoon"><img src="http://banners.wunderground.com/weathersticker/sunandmoon_both/language/www/US/MD/College_Park.gif" alt="Click for College Park, Maryland Forecast" width="250" /></a> -->


	</div>
	<div class="cleared"></div>
	</div>
	</div>

<div class="cleared"></div>
</div>
</div>